package entities;
// Generated Apr 20, 2022, 11:27:46 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name = "HoaDon", schema = "dbo", catalog = "ElteeStore")
public class HoaDon implements java.io.Serializable {

	private Integer idhd;
	private KhachHang khachHang;
	private NhanVien nhanVien;
	private Double tongTien;
	private Date thoiDiemLap;
	private Integer giamGia;
	private Set<ChiTietHoaDon> chiTietHoaDons = new HashSet<ChiTietHoaDon>(0);
	private Set<ChiTietHoaDon> chiTietHoaDons_1 = new HashSet<ChiTietHoaDon>(0);

	public HoaDon() {
	}

	public HoaDon(NhanVien nhanVien) {
		this.nhanVien = nhanVien;
	}

	public HoaDon(KhachHang khachHang, NhanVien nhanVien, Double tongTien, Date thoiDiemLap, Integer giamGia,
			Set<ChiTietHoaDon> chiTietHoaDons, Set<ChiTietHoaDon> chiTietHoaDons_1) {
		this.khachHang = khachHang;
		this.nhanVien = nhanVien;
		this.tongTien = tongTien;
		this.thoiDiemLap = thoiDiemLap;
		this.giamGia = giamGia;
		this.chiTietHoaDons = chiTietHoaDons;
		this.chiTietHoaDons_1 = chiTietHoaDons_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDHD", unique = true, nullable = false)
	public Integer getIdhd() {
		return this.idhd;
	}

	public void setIdhd(Integer idhd) {
		this.idhd = idhd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDKH")
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNV", nullable = false)
	public NhanVien getNhanVien() {
		return this.nhanVien;
	}

	public void setNhanVien(NhanVien nhanVien) {
		this.nhanVien = nhanVien;
	}

	@Column(name = "TongTien", precision = 53, scale = 0)
	public Double getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(Double tongTien) {
		this.tongTien = tongTien;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiDiemLap", length = 23)
	public Date getThoiDiemLap() {
		return this.thoiDiemLap;
	}

	public void setThoiDiemLap(Date thoiDiemLap) {
		this.thoiDiemLap = thoiDiemLap;
	}

	@Column(name = "GiamGia")
	public Integer getGiamGia() {
		return this.giamGia;
	}

	public void setGiamGia(Integer giamGia) {
		this.giamGia = giamGia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoaDon")
	public Set<ChiTietHoaDon> getChiTietHoaDons() {
		return this.chiTietHoaDons;
	}

	public void setChiTietHoaDons(Set<ChiTietHoaDon> chiTietHoaDons) {
		this.chiTietHoaDons = chiTietHoaDons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoaDon")
	public Set<ChiTietHoaDon> getChiTietHoaDons_1() {
		return this.chiTietHoaDons_1;
	}

	public void setChiTietHoaDons_1(Set<ChiTietHoaDon> chiTietHoaDons_1) {
		this.chiTietHoaDons_1 = chiTietHoaDons_1;
	}

}
