package entities;
// Generated Apr 20, 2022, 11:27:46 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiSp generated by hbm2java
 */
@Entity
@Table(name = "LoaiSP", schema = "dbo", catalog = "ElteeStore")
public class LoaiSp implements java.io.Serializable {

	private Integer idloaiSp;
	private String tenLoaiSp;
	private String hinh;
	private Set<SanPham> sanPhams = new HashSet<SanPham>(0);
	private Set<SanPham> sanPhams_1 = new HashSet<SanPham>(0);

	public LoaiSp() {
	}

	public LoaiSp(String tenLoaiSp) {
		this.tenLoaiSp = tenLoaiSp;
	}

	public LoaiSp(String tenLoaiSp, String hinh, Set<SanPham> sanPhams, Set<SanPham> sanPhams_1) {
		this.tenLoaiSp = tenLoaiSp;
		this.hinh = hinh;
		this.sanPhams = sanPhams;
		this.sanPhams_1 = sanPhams_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDLoaiSP", unique = true, nullable = false)
	public Integer getIdloaiSp() {
		return this.idloaiSp;
	}

	public void setIdloaiSp(Integer idloaiSp) {
		this.idloaiSp = idloaiSp;
	}

	@Column(name = "TenLoaiSP", nullable = false)
	public String getTenLoaiSp() {
		return this.tenLoaiSp;
	}

	public void setTenLoaiSp(String tenLoaiSp) {
		this.tenLoaiSp = tenLoaiSp;
	}

	@Column(name = "Hinh")
	public String getHinh() {
		return this.hinh;
	}

	public void setHinh(String hinh) {
		this.hinh = hinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiSp")
	public Set<SanPham> getSanPhams() {
		return this.sanPhams;
	}

	public void setSanPhams(Set<SanPham> sanPhams) {
		this.sanPhams = sanPhams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiSp")
	public Set<SanPham> getSanPhams_1() {
		return this.sanPhams_1;
	}

	public void setSanPhams_1(Set<SanPham> sanPhams_1) {
		this.sanPhams_1 = sanPhams_1;
	}
	@Override
	public String toString() {
		return tenLoaiSp;
	}
}
