package entities;
// Generated Apr 20, 2022, 11:27:46 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "NhanVien", schema = "dbo", catalog = "ElteeStore")
public class NhanVien implements java.io.Serializable {

	private Integer idnv;
	private String tenNv;
	private String email;
	private String taiKhoan;
	private String matKhau;
	private Boolean quyen;
	private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);
	private Set<HoaDon> hoaDons_1 = new HashSet<HoaDon>(0);
	private Set<HoaDon> hoaDons_2 = new HashSet<HoaDon>(0);
	private Set<HoaDon> hoaDons_3 = new HashSet<HoaDon>(0);

	public NhanVien() {
	}

	public NhanVien(String tenNv) {
		this.tenNv = tenNv;
	}

	public NhanVien(String tenNv, String email, String taiKhoan, String matKhau, Boolean quyen,
			Set<HoaDon> hoaDons, Set<HoaDon> hoaDons_1, Set<HoaDon> hoaDons_2, Set<HoaDon> hoaDons_3) {
		this.tenNv = tenNv;
		this.email = email;
		this.taiKhoan = taiKhoan;
		this.matKhau = matKhau;
		this.quyen = quyen;
		this.hoaDons = hoaDons;
		this.hoaDons_1 = hoaDons_1;
		this.hoaDons_2 = hoaDons_2;
		this.hoaDons_3 = hoaDons_3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDNV", unique = true, nullable = false)
	public Integer getIdnv() {
		return this.idnv;
	}

	public void setIdnv(Integer idnv) {
		this.idnv = idnv;
	}

	@Column(name = "TenNV", nullable = false)
	public String getTenNv() {
		return this.tenNv;
	}

	public void setTenNv(String tenNv) {
		this.tenNv = tenNv;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TaiKhoan")
	public String getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(String taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "MatKhau")
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Column(name = "Quyen")
	public Boolean getQuyen() {
		return this.quyen;
	}

	public void setQuyen(Boolean quyen) {
		this.quyen = quyen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanVien")
	public Set<HoaDon> getHoaDons() {
		return this.hoaDons;
	}

	public void setHoaDons(Set<HoaDon> hoaDons) {
		this.hoaDons = hoaDons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanVien")
	public Set<HoaDon> getHoaDons_1() {
		return this.hoaDons_1;
	}

	public void setHoaDons_1(Set<HoaDon> hoaDons_1) {
		this.hoaDons_1 = hoaDons_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanVien")
	public Set<HoaDon> getHoaDons_2() {
		return this.hoaDons_2;
	}

	public void setHoaDons_2(Set<HoaDon> hoaDons_2) {
		this.hoaDons_2 = hoaDons_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanVien")
	public Set<HoaDon> getHoaDons_3() {
		return this.hoaDons_3;
	}

	public void setHoaDons_3(Set<HoaDon> hoaDons_3) {
		this.hoaDons_3 = hoaDons_3;
	}

}
