package entities;
// Generated Apr 20, 2022, 11:27:46 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name = "SanPham", schema = "dbo", catalog = "ElteeStore")
public class SanPham implements java.io.Serializable {

	private Integer idsp;
	private LoaiSp loaiSp;
	private String tenSp;
	private int giaBan;
	private Integer slton;
	private String hinh;
	private Set<ChiTietHoaDon> chiTietHoaDons = new HashSet<ChiTietHoaDon>(0);
	private Set<ChiTietHoaDon> chiTietHoaDons_1 = new HashSet<ChiTietHoaDon>(0);

	public SanPham() {
	}

	public SanPham(LoaiSp loaiSp, String tenSp, int giaBan) {
		this.loaiSp = loaiSp;
		this.tenSp = tenSp;
		this.giaBan = giaBan;
	}

	public SanPham(LoaiSp loaiSp, String tenSp, int giaBan, Integer slton, String hinh,
			Set<ChiTietHoaDon> chiTietHoaDons, Set<ChiTietHoaDon> chiTietHoaDons_1) {
		this.loaiSp = loaiSp;
		this.tenSp = tenSp;
		this.giaBan = giaBan;
		this.slton = slton;
		this.hinh = hinh;
		this.chiTietHoaDons = chiTietHoaDons;
		this.chiTietHoaDons_1 = chiTietHoaDons_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDSP", unique = true, nullable = false)
	public Integer getIdsp() {
		return this.idsp;
	}

	public void setIdsp(Integer idsp) {
		this.idsp = idsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDLoaiSP", nullable = false)
	public LoaiSp getLoaiSp() {
		return this.loaiSp;
	}

	public void setLoaiSp(LoaiSp loaiSp) {
		this.loaiSp = loaiSp;
	}

	@Column(name = "TenSP", nullable = false)
	public String getTenSp() {
		return this.tenSp;
	}

	public void setTenSp(String tenSp) {
		this.tenSp = tenSp;
	}

	@Column(name = "GiaBan", nullable = false)
	public int getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(int giaBan) {
		this.giaBan = giaBan;
	}

	@Column(name = "SLTon")
	public Integer getSlton() {
		return this.slton;
	}

	public void setSlton(Integer slton) {
		this.slton = slton;
	}

	@Column(name = "Hinh")
	public String getHinh() {
		return this.hinh;
	}

	public void setHinh(String hinh) {
		this.hinh = hinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanPham")
	public Set<ChiTietHoaDon> getChiTietHoaDons() {
		return this.chiTietHoaDons;
	}

	public void setChiTietHoaDons(Set<ChiTietHoaDon> chiTietHoaDons) {
		this.chiTietHoaDons = chiTietHoaDons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanPham")
	public Set<ChiTietHoaDon> getChiTietHoaDons_1() {
		return this.chiTietHoaDons_1;
	}

	public void setChiTietHoaDons_1(Set<ChiTietHoaDon> chiTietHoaDons_1) {
		this.chiTietHoaDons_1 = chiTietHoaDons_1;
	}

}
